### ISSUE TITLE
Python 3.12 Spae installation error

### ISSUE THREAD

**Issue by gbouras13** [linsalrob/sphae#17]
Spae won't install on python v3.12. It works fine on 3.11. MacOS M1 chip MacBook Pro. 

I used `pip install -e .`

```
Obtaining file:///Users/a1667917/Documents/spae
  Preparing metadata (setup.py) ... done
Collecting snaketool-utils>=0.0.4 (from phage-genome-assembly==1.0.0)
  Using cached snaketool_utils-0.0.4-py3-none-any.whl.metadata (1.7 kB)
Collecting snakemake>=7.14.0 (from phage-genome-assembly==1.0.0)
  Using cached snakemake-7.32.4-py3-none-any.whl
Collecting pyyaml==6.0 (from phage-genome-assembly==1.0.0)
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/a1667917/mambaforge/envs/spae/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/a1667917/mambaforge/envs/spae/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/a1667917/mambaforge/envs/spae/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 318, in run
          self.find_sources()
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
          mm.run()
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 548, in run
          self.add_defaults()
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/private/var/folders/t9/ns8v1yq93_j7nhlnbcntkp6c0000gq/T/pip-build-env-vidoxi19/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by npbhavya** [comment]
fixed now
